export enum EWebsocketMessageType {
	RIDDLE_PUBLISHED = "RIDDLE_PUBLISHED",
	RIDDLE_SOLVED = "RIDDLE_SOLVED",
	RIDDLE_PUBLISHING = "RIDDLE_PUBLISHING",
	USER_SUBMISSION_UPDATE = "USER_SUBMISSION_UPDATE",
}
