name: on-chain-riddle
volumes:
  db_storage:
  redis_data:

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=hsha19jkIh73hsk
      - POSTGRES_DB=on-chain-riddle-db
    ports:
      - 5177:5432
    volumes:
      - db_storage:/var/lib/postgresql/data
